apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
