version: '3.9'

services:
  postgres:
    restart: always
    ports:
      - "5432:5432"
    image: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1q2w3e
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic

  kibana:
    image: kibana:8.2.2
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  postgresql-data:
    driver: local
  mongodb-data:
    driver: local
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge

