apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  name: zookeeper-stateful
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper
          imagePullPolicy: Always
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-configmap
                  key: ZOOKEEPER_CLIENT_PORT
            - name: ZOOKEEPER_TICK_TIME
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-configmap
                  key: ZOOKEEPER_TICK_TIME
            - name: ZOOKEEPER_SYNC_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-configmap
                  key: ZOOKEEPER_SYNC_LIMIT
      volumes:
        - name: zookeeper-disk
          hostPath:
            path: /data
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-disk
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi