apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: gzn2zjsn/task-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_LIQUIBASE_URL
              valueFrom:
                configMapKeyRef:
                  name: task-service-configmap
                  key: APP_LIQUIBASE_URL
            - name: APP_DATA_MONGODB_AUTHENTICATION-DATABASE
              valueFrom:
                configMapKeyRef:
                  name: task-service-configmap
                  key: APP_DATA_MONGODB_AUTHENTICATION-DATABASE
            - name: APP_DATA_MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: task-service-configmap
                  key: APP_DATA_MONGODB_PORT
            - name: APP_DATA_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: task-service-configmap
                  key: APP_DATA_MONGODB_DATABASE
            - name: APP_DATA_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: task-service-configmap
                  key: APP_DATA_MONGODB_HOST
            - name: APP_KAFKA_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  name: task-service-configmap
                  key: APP_KAFKA_BOOTSTRAP-SERVERS
            - name: APP_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ts-mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: APP_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ts-mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: APP_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: task-service-configmap
                  key: APP_DATA_REDIS_PORT
            - name: APP_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: task-service-configmap
                  key: APP_DATA_REDIS_HOST
