scrape_configs:
  - job_name: 'Inventory Service input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: [ 'inventory-service:8080' ]
        labels:
          application: 'Inventory Service Application'