apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_BROKER_ID
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_ADVERTISED_LISTENERS
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_ZOOKEEPER_CONNECT
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR