apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: kafka-configmap
data:
  KAFKA_BROKER_ID: '2'
  KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-service:9092'
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT'
  KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-service:2181'
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'