apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      serviceAccountName: order-service-service-account
      containers:
        - name: order-service
          image: gzn2zjsn/order-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-configmap
                  key: APP_JDBC_URL
            - name: APP_R2DBC_URL
              valueFrom:
                configMapKeyRef:
                  name: order-service-configmap
                  key: APP_R2DBC_URL
            - name: APP_KAFKA_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  name: order-service-configmap
                  key: APP_KAFKA_BOOTSTRAP-SERVERS
            - name: SETTINGS_TASK-SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-service-configmap
                  key: SETTINGS_TASK-SERVICE_HOST
            - name: SETTINGS_TASK-SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: order-service-configmap
                  key: SETTINGS_TASK-SERVICE_PORT
            - name: APP_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: os-postgres-secret
                  key: POSTGRES_USER
            - name: APP_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: os-postgres-secret
                  key: POSTGRES_PASSWORD

