apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: istio-ingress
spec:
  rules:
    - http:
        paths:
          - path: /task-api
            pathType: Prefix
            backend:
              service:
                name: task-service
                port:
                  number: 8080
          - path: /order-api
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 8080