apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ts-redis-stateful
spec:
  serviceName: ts-redis
  replicas: 3
  selector:
    matchLabels:
      app: ts-redis
  template:
    metadata:
      labels:
        app: ts-redis
    spec:
      containers:
        - name: ts-redis
          image: redis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
      volumes:
        - name: task-service-cache-disk
          hostPath:
            path: /data
  volumeClaimTemplates:
    - metadata:
        name: task-service-cache-disk
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi