apiVersion: v1
kind: Service
metadata:
  name: axonserver-service
  labels:
    app: axonserver
spec:
  ports:
    - name: grpc
      port: 8124
      targetPort: 8124
  clusterIP: None
  selector:
    app: axonserver