apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: is-actions-runner-crb
  namespace: actions-runner-system
subjects:
  - kind: ServiceAccount
    name: is-actions-runner-sa
    namespace: actions-runner-system
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io