apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: is-actions-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: is-actions-runner-sa
      automountServiceAccountToken: true
      repository: gznznzjsn/inventory-service
      labels:
        - k8s-api
      workVolumeClaimTemplate:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi